name: FibCalc_workflow
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-push-images:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            michas12/zadanie_1
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          cache-from: type=registry,ref=docker.io/michas12/zadanie_1:cache
          cache-to: type=registry,ref=docker.io/michas12/zadanie_1:cache,mode=max
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}